services:
  # Keycloak Service
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command:
      - "start-dev"
      - "--import-realm"
      - "--health-enabled=true"
    environment:
      DB_VENDOR: mysql
      DB_ADDR: metahive-metahive.f.aivencloud.com
      DB_PORT: 20529
      DB_DATABASE: keycloak
      DB_USER: avnadmin
      DB_PASSWORD: AVNS_QzWYo08q2dMv5gho4od
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181
    ports:
      - "8181:8181"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/